alias vim="nvim"
alias nix="nix --extra-experimental-features nix-command --extra-experimental-features flakes"
alias ll="ls -la"
alias cat="bat"
alias aliases="bat ~/.config/dotfiles/aliases.zsh"
alias lg="lazygit"
alias k="kubectl"
alias g="git"
