alias nix="nix --extra-experimental-features nix-command --extra-experimental-features flakes"
alias ll="ls -la"
alias c="cd /Users/manuel/code"
alias config="code /Users/manuel/.config/"

# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix

export PATH=/opt/homebrew/bin:$PATH
eval "$(starship init zsh)"

# Activate zsh autosuggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh