if [ -f ~/.config/dotfiles/aliases.zsh ]; then
  source ~/.config/dotfiles/aliases.zsh
fi

# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix

export PATH=/opt/homebrew/bin:$PATH
eval "$(starship init zsh)"

# Activate zsh autosuggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# TODO: Check how to install syntax highlighting via Nix instead brew
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Activate mcfly
eval "$(mcfly init zsh)"