[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
opacity = 0.9
blur = true
option_as_alt = "Both"
decorations = "Buttonless"

[font]
normal = { family = "Hack Nerd Font Mono" }
size = 15
