[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
opacity = 0.9
blur = true
option_as_alt = "Both"

[shell]
program = "/Users/manuel/.nix-profile/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main"]

[font]
normal = { family = "Hack Nerd Font Mono" }
size = 15